# permissions for end users to view eventsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventsubscription-viewer-role
rules:
- apiGroups:
  - redfish.metal3.io
  resources:
  - eventsubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redfish.metal3.io
  resources:
  - eventsubscriptions/status
  verbs:
  - get
