# permissions for end users to edit eventsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventsubscription-editor-role
rules:
- apiGroups:
  - redfish.metal3.io
  resources:
  - eventsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redfish.metal3.io
  resources:
  - eventsubscriptions/status
  verbs:
  - get
